Add pet function
RotemZohar/menahem-front pull request #12
Opened 2022-05-21 19:43 UTC by michal-zv

2022-05-22 19:54 UTC, michal-zv commented
הדבר היחיד שנשאר לעשות זה לשמור את החיה ביוזר ואת היוזר בחיה
ואין לי מושג איך
אשמח לעזרה

2022-05-23 11:27 UTC, michal-zv commented on src/components/pets/AddPetForm.tsx
> +      weight === 0 ||
שיניתי

2022-05-23 11:29 UTC, RotemZohar requested changes

2022-05-23 11:29 UTC, RotemZohar commented on src/components/pets/AddPetForm.tsx
> +      post("/pets/new", {
תראי את ההערה בבאק

2022-05-23 13:57 UTC, michal-zv commented on src/components/pets/AddPetForm.tsx
> +      post("/pets/new", {
שיניתי

2022-05-23 21:25 UTC, michal-zv commented on src/App.tsx
> +          <Route path="pets/new" element={<AddPetForm />} />
שיניתי

2022-05-23 21:27 UTC, michal-zv commented on src/components/pets/AddPetForm.tsx
> +  const onSubmit = (e: any) => {
שיניתי

2022-05-25 11:18 UTC, michal-zv commented on src/components/pets/AddPetForm.tsx
> +      alert("Please insert all fields!");
הוספתי TODO

2022-05-25 11:18 UTC, michal-zv commented on src/components/pets/AddPetForm.tsx
> +          if (res === "Created") {
לא בטוחה איך לעשות את זה אז הוספתי TODO

2022-05-25 11:40 UTC, michal-zv commented on src/components/pets/AddPetForm.tsx
> +  }, [species, breed, currentBreedList]);
לא הנבתי אשמח להסבר

2022-05-25 12:40 UTC, merged